### ISSUE TITLE
Add a new category to each card

### ISSUE THREAD

**Issue by S0Sllama** [adunderwood/Flower-War#24]
Add a category to each card to show what the card does. ie, does it move a player around the board, change the number of tokens a player has, change how battle works (deal with escape or battle statistics), etc. This will make things easier to organize with cards.

**Comment by adunderwood** [comment]
Here's the spreadsheet that I'm working on these with. One day I'll work in the right place but not today...

https://docs.google.com/spreadsheets/d/13QkOFg3vqgfPxFSxwA8gbKnEOc7bTxlYOsMEjkXmk2I/edit#gid=0
